---
json_rpc_url: https://api.devnet.solana.com
websocket_url: ''
keypair_path: dadQbp3MYxDiD4wdFoLMeaJSv6EKtgF1z2QtPbJgyX3.json
address_labels:
  '11111111111111111111111111111111': System Program
commitment: confirmed
